all: Fix "error: cast between incompatible function types" errors with gcc8
gcc8 does not like it when casting from a function with no arguments to one
which actually expects arguments, causing it to throw errors like these:

drv-fake-compass.c: In function ‘first_values’:
drv-fake-compass.c:66:51: error: cast between incompatible function types from ‘gboolean (*)(void)’ {aka ‘int (*)(void)’} to ‘gboolean (*)(void *)’ {aka ‘int (*)(void *)’} [-Werror=cast-function-type]
  drv_data->timeout_id = g_timeout_add_seconds (1, (GSourceFunc) compass_changed, NULL);
                                                   ^

This fixes this.